// Generated by CoffeeScript 1.6.2
(function() {
  var Connection;

  Connection = (function() {
    /*
    */
    function Connection(connection, cid, secret) {
      this.connection = connection;
      this.cid = cid;
      this.secret = secret;
      this._tunnelQueue = [];
    }

    /*
    */


    Connection.prototype.addTunnel = function(cid, secret, connection, callback) {
      if ((cid !== this.cid) || (this.secret !== secret)) {
        return callback(new Error("CID or secret is incorrect"));
      }
      if (!this._tunnelQueue.length) {
        return callback();
      }
      this._tunnelQueue.shift()(null, connection);
      return callback();
    };

    /*
    */


    Connection.prototype.getTunnel = function(callback) {
      this._tunnelQueue.push(callback);
      return this.connection.write("1");
    };

    return Connection;

  })();

  module.exports = Connection;

}).call(this);
