// Generated by CoffeeScript 1.6.2
(function() {
  var ChunnelClient, ChunnelServer, EventEmitter, HttpServers, SocketServer, hooks, mdns, net, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  net = require("net");

  ChunnelClient = require("./client");

  EventEmitter = require("events").EventEmitter;

  SocketServer = require("../socket").Server;

  HttpServers = require("./httpServers");

  hooks = require("hooks");

  mdns = require("mdns");

  _ = require("underscore");

  ChunnelServer = (function(_super) {
    __extends(ChunnelServer, _super);

    /*
    */


    function ChunnelServer(options) {
      this.options = options;
      ChunnelServer.__super__.constructor.call(this);
      this._setupHooks();
      this.password = options.password;
      this._clients = [];
      this._cid = 0;
      this._httpServers = new HttpServers();
      this.on("client", this.connectClient);
      this.on("connection", this._onHttpConnection);
    }

    /*
    */


    ChunnelServer.prototype._setupHooks = function() {};

    /*
    */


    ChunnelServer.prototype.listen = function(port) {
      this.port = port != null ? port : 9526;
      ChunnelServer.__super__.listen.call(this, port);
      console.log("chunnel server listening on port " + port + " " + (this.secret ? 'with secret' : ''));
      if (this.options.broadcast) {
        this.broadcast();
      }
      return this;
    };

    /*
    */


    ChunnelServer.prototype.use = function(module) {
      return module(this);
    };

    /*
    */


    ChunnelServer.prototype.connectClient = function(message, socket) {
      var client, domain, password,
        _this = this;

      domain = message.domain;
      password = message.password;
      if (password !== this.password) {
        return socket.error("Incorrect password");
      }
      console.log("client \"" + (message.username || "unknown") + "\" connected on domain " + domain);
      if (!this._httpServers.hasClient(domain)) {
        return socket.error(new Error("cannot listen on domain " + domain + " (might already be taken)"));
      }
      this._clients[String(++this._cid)] = client = new ChunnelClient(socket, domain);
      this._httpServers.listen(domain, client);
      client.once("close", function() {
        return _this._clients.splice(_this._clients.indexOf(client), 1);
      });
      return socket.send("success", {
        cid: this._cid,
        secret: client.secret
      });
    };

    /*
    */


    ChunnelServer.prototype.broadcast = function() {
      if (this._broadcasting) {
        return;
      }
      console.log("broadcasting server using multicast");
      this._broadcasting = true;
      return mdns.createAdvertisement(mdns.tcp("chunnel"), this.port).start();
    };

    /*
    */


    ChunnelServer.prototype._onHttpConnection = function(message, socket) {
      var client;

      if (!(client = this._clients[String(message.cid)])) {
        return socket.error(new Error("cid does not exist"));
      }
      console.log("adding tunneled http connection for " + client._domain);
      return client.addConnection(socket.connection, message.secret);
    };

    /*
    */


    ChunnelServer.prototype._setupHooks = function() {
      _.extend(this, hooks);
      return this.hook("connectClient", this.connectClient);
    };

    return ChunnelServer;

  })(SocketServer);

  module.exports = function(options) {
    return new ChunnelServer(options);
  };

}).call(this);
