// Generated by CoffeeScript 1.6.2
(function() {
  var Keys;

  Keys = (function() {
    function Keys() {}

    /*
    */


    Keys.prototype.generate = function() {
      return crypto.createHash('md5').update(Date.now() + Math.random()).digest("hex");
    };

    return Keys;

  })();

  module.exports = Keys;

}).call(this);
