// Generated by CoffeeScript 1.6.2
(function() {
  var Client, Server, net;

  Client = require("./client");

  Server = require("./server");

  net = require("net");

  module.exports = {
    connect: function(port, hostname) {
      return new Client(net.connect(Number(port), hostname));
    },
    listen: function(port) {
      return new Server().listen(port);
    },
    Server: Server
  };

}).call(this);
